"""Extended Data table: outcomes with the largest concordance loss under the 2-year washout
(reverse-causality check). Re-derives per-outcome baseline vs 2-year-washout Harrell C from the
frozen seed-averaged disjoint_split_v1 test hazards, asserts the published aggregate anchors, then
writes draft/tab_washout_drops.tex (the 19 outcomes that dropped >0.05) + draft/washout_2yr_source_data.csv
(all 388). Read-only on the run outputs.
"""
import json, os
from pathlib import Path
import numpy as np
import pandas as pd
from ukb_disease.paths import UKB_ROOT

RUNS = f"{UKB_ROOT}/runs_cox"
SEEDS = [42, 123, 456, 789]
OUT = str(Path(__file__).resolve().parent.parent / "draft")
PHECODE_MAP = f"{UKB_ROOT}/metadata/Phecode_mapX_filtered.csv"
CAT = {"MS": "Musculoskeletal", "GI": "Gastrointestinal", "GU": "Genitourinary", "RE": "Respiratory",
       "DE": "Dermatological", "SO": "Sense organs", "CV": "Cardiovascular", "NS": "Neurological",
       "EM": "Endocrine/Metab", "CA": "Neoplasms", "MB": "Mental", "BI": "Blood/Immune",
       "ID": "Infections", "SS": "Symptoms", "time": "Mortality"}


def esc(s):
    s = str(s)
    for a, b in [("&", r"\&"), ("%", r"\%"), ("_", r"\_"), ("#", r"\#")]:
        s = s.replace(a, b)
    return s.replace("/", "/\\allowbreak ")


def harrell(h, t, e):  # faithful concordance_benchmark.harrell_counts
    fin = np.isfinite(h); ev = np.where((e == 1) & fin)[0]; conc = comp = 0.0
    for a in ev:
        b = ((t > t[a]) | ((t == t[a]) & (e == 0))) & fin
        if not b.any():
            continue
        comp += int(b.sum()); d = h[a] - h[b]
        conc += float((d > 0).sum()) + 0.5 * float((d == 0).sum())
    return (conc / comp) if comp > 0 else np.nan


def main():
    dirs = [f"{RUNS}/embedding_disjoint_split_seed{s}" for s in SEEDS]
    H = np.stack([np.load(f"{d}/test_hazards.npy") for d in dirs]).mean(0)
    T = np.load(f"{dirs[0]}/test_event_times.npy"); E = np.load(f"{dirs[0]}/test_is_event.npy")
    M = np.load(f"{dirs[0]}/test_eval_mask.npy"); phe = json.load(open(f"{dirs[0]}/config.json"))["phecodes"]
    mp = pd.read_csv(PHECODE_MAP, usecols=["Phecode", "PhecodeString"])
    name = dict(zip(mp.Phecode, mp.PhecodeString)); name["time_to_death"] = "All-cause mortality"

    rows = []
    for j, p in enumerate(phe):
        m = M[:, j].astype(bool); nev = int((E[m, j] == 1).sum())
        if int(m.sum()) < 10 or nev < 1:
            continue
        bc = harrell(H[m, j], T[m, j], E[m, j])
        wm = m & ((E[:, j] == 0) | ((E[:, j] == 1) & (T[:, j] > 2.0)))
        nevw = int((E[wm, j] == 1).sum())
        wc = harrell(H[wm, j], T[wm, j], E[wm, j]) if (int(wm.sum()) >= 10 and nevw >= 1) else np.nan
        disp = name.get(p, p).split("[")[0].strip().rstrip("*").strip()
        rows.append(dict(phecode=p, disease=disp, category=CAT.get(p.split("_")[0], "Other"),
                         n_event=nev, n_event_wash=nevw, dropped_le2yr=nev - nevw,
                         baseline_c=bc, washout_c=wc, delta_c=(wc - bc) if np.isfinite(wc) else np.nan))
    df = pd.DataFrame(rows)

    # --- guardrail: reproduce the published aggregate anchors before writing anything ---
    d = df.delta_c.dropna()
    assert len(df) == 388, f"expected 388 evaluable, got {len(df)}"
    assert abs(df.baseline_c.mean() - 0.68803) < 5e-4, df.baseline_c.mean()
    assert abs(df.washout_c.mean() - 0.68485) < 5e-4, df.washout_c.mean()
    assert (d < -0.05).sum() == 19 and (d < -0.10).sum() == 1, ((d < -0.05).sum(), (d < -0.10).sum())
    print(f"anchors OK: baseline {df.baseline_c.mean():.5f} washout {df.washout_c.mean():.5f} "
          f"drops>0.05 {(d<-0.05).sum()} >0.10 {(d<-0.10).sum()}")

    df.sort_values("delta_c").to_csv(f"{OUT}/washout_2yr_source_data.csv", index=False)

    big = df[df.delta_c < -0.05].sort_values("delta_c")
    L = ["% AUTO-GENERATED by figbuild/gen_washout_table.py. Do not hand-edit.",
         "\\begin{table}[H]\\centering\\footnotesize",
         "\\exttablecaption{\\textbf{Outcomes with the largest concordance loss under the two-year "
         "washout.} Of the 388 evaluable outcomes, the 19 whose six-year concordance fell by more than "
         "0.05 when every incident case diagnosed within two years of the wrist recording was excluded "
         "(the reverse-causality check in the Discussion). Across all 388 outcomes the median change was "
         "$-0.004$ and the phenome-wide mean was almost unchanged (0.685 versus 0.688); one outcome, "
         "appendicitis, fell by more than 0.10. The larger drops are confined to uncommon conditions: each "
         "rests on at most 63 incident test cases, most on fewer than 20, several start from a baseline "
         "concordance near chance, and none is a neurodegenerative or cardiometabolic outcome featured in "
         "the analysis, so on few events these per-outcome estimates are imprecise. Columns give the "
         "incident test cases, the cases removed by the washout, the baseline and washout concordance, and "
         "their difference; outcomes are ordered by the size of the drop.}",
         "\\label{exttab:washout_drops}",
         "\\begin{tabular}{@{}p{5.3cm} l r r r r r@{}}\\toprule",
         "Outcome & Category & $n_{\\mathrm{ev}}$ & Removed & $C$ & $C$ washout & $\\Delta C$ \\\\\\midrule"]
    for _, r in big.iterrows():
        L.append(f"{esc(r.disease)} & {esc(r.category)} & {int(r.n_event)} & {int(r.dropped_le2yr)} & "
                 f"{r.baseline_c:.3f} & {r.washout_c:.3f} & ${r.delta_c:+.3f}$ \\\\")
    L += ["\\bottomrule\\end{tabular}\\end{table}"]
    open(f"{OUT}/tab_washout_drops.tex", "w").write("\n".join(L) + "\n")
    print(f"wrote {OUT}/tab_washout_drops.tex ({len(big)} rows) + washout_2yr_source_data.csv ({len(df)} rows)")


if __name__ == "__main__":
    main()
