"""Write the genetics supplementary table (draft/tab_genetics.tex): per-disease
fusion numbers with FDR, plus the matched PRS->phecode crosswalk.

Set UKB_ROOT to point at the data root. Run with python3.
"""
import os
import json
from pathlib import Path
import numpy as np
import pandas as pd

UKB_ROOT = os.environ.get("UKB_ROOT", "data")
CF = Path(f"{UKB_ROOT}/crossfit")
HERE = Path(__file__).resolve().parent
OUT = Path(__file__).resolve().parent.parent.parent / "draft" / "tab_genetics.tex"
LABEL = {
    "GI_525.1": "Coeliac disease", "EM_202.1": "Type 1 diabetes", "SO_375.11": "Glaucoma (open-angle)",
    "CV_402": "Hypertension (elevated BP)", "GI_522.11": "Crohn's disease", "SO_375.1": "Glaucoma",
    "CV_416.212": "Atrial fibrillation (persistent)", "CV_416.211": "Atrial fibrillation (paroxysmal)",
    "CV_416.2": "Atrial fibrillation", "DE_664.4": "Psoriasis", "CV_404.2": "Coronary atherosclerosis",
    "CV_404.11": "Acute myocardial infarction", "RE_475": "Asthma", "EM_202.2": "Type 2 diabetes",
    "CV_404.1": "Myocardial infarction", "CV_440.3": "Pulmonary embolism", "GI_522.12": "Ulcerative colitis",
    "CV_401.1": "Essential hypertension", "CV_404": "Ischaemic heart disease", "CA_103": "Melanoma/skin cancer",
    "MS_705.1": "Rheumatoid arthritis", "SO_374.5": "Macular degeneration", "NS_324.11": "Parkinson's disease",
    "NS_328.1": "Dementia", "CV_431.11": "Ischaemic stroke", "NS_328.11": "Alzheimer's disease",
}


def bh_fdr(p):
    p = np.asarray(p, float); n = len(p); order = np.argsort(p)
    ranked = p[order] * n / (np.arange(n) + 1)
    q = np.minimum.accumulate(ranked[::-1])[::-1]
    out = np.empty(n); out[order] = np.clip(q, 0, 1); return out


def esc(s):
    return str(s).replace("&", "\\&").replace("%", "\\%").replace("_", "\\_")


def main():
    d = pd.read_csv(CF / "perdisease_eur" / "perdisease_ci.csv")
    d["p_two"] = 2 * np.minimum(d.p_pos, 1 - d.p_pos)
    d["fdr"] = bh_fdr(d.p_two.values)
    d["label"] = [LABEL.get(p, p) for p in d.phecode]
    d = d.sort_values("delta", ascending=False)

    xwalk = {k: v for k, v in json.load(open(HERE / "prs_phecode_crosswalk.json")).items()
             if not k.startswith("_")}
    fm = pd.read_csv(HERE / "prs_field_map.csv")
    fid = {}  # trait -> (std_field, enh_field)
    for tr, g in fm[fm.is_disease == "yes"].groupby("trait_short"):
        s = g[g.kind == "Standard"]["field_id"]; e = g[g.kind == "Enhanced"]["field_id"]
        fid[tr] = (str(s.iloc[0]) if len(s) else "--", str(e.iloc[0]) if len(e) else "--")

    L = []
    L.append("% AUTO-GENERATED by ukb_disease.genetics.make_table. Do not hand-edit.")
    # Table 1: per-disease fusion result
    L.append("\\begin{table}[H]\\centering\\footnotesize")
    L.append("\\exttablecaption{\\textbf{Per-disease genetics fusion result (matched Standard PRS, European "
             "genetic ancestry, held-out test set).} $C$ values are leakage-safe out-of-fold "
             "concordance for the wrist embedding alone, the PRS alone, and the learned fusion "
             "[wrist hazard, PRS]. $\\Delta C$ is fusion minus wrist with a 95\\% subject bootstrap "
             "interval; FDR is Benjamini--Hochberg across the 26 outcomes, and diseases in "
             "\\textbf{bold} are significant at FDR $<0.05$. The aggregate effect "
             "($+0.042$, 95\\% CI $+0.021$ to $+0.069$) is the robust claim; per-disease FDR is "
             "conservative on these incident-case counts.}")
    L.append("\\label{exttab:genetics_fusion}")
    L.append("\\begin{tabular}{@{}lrrrrrr@{}}\\toprule")
    L.append("Outcome & $n_{\\mathrm{ev}}$ & $C$ wrist & $C$ PRS & $C$ fusion & $\\Delta C$ (95\\% CI) & FDR \\\\\\midrule")
    for _, r in d.iterrows():
        # bold diseases significant after Benjamini-Hochberg correction (FDR < 0.05)
        name = f"\\textbf{{{esc(r.label)}}}" if r.fdr < 0.05 else esc(r.label)
        L.append(f"{name} & {int(r.n_ev)} & {r.c_embed:.3f} & {r.c_prs_only:.3f} & "
                 f"{r.c_fusion:.3f} & {r.delta:+.3f} ({r.delta_lo:+.3f}, {r.delta_hi:+.3f}) & "
                 f"{r.fdr:.3f} \\\\")
    L.append("\\bottomrule\\end{tabular}\\end{table}")

    # Table 2: PRS -> phecode crosswalk
    L.append("\\begin{table}[H]\\centering\\footnotesize")
    L.append("\\exttablecaption{\\textbf{Disease-matched PRS to phecode crosswalk.} Each polygenic risk "
             "score (UK Biobank Standard release field) matched by hand to the corresponding "
             "incident phecode(s) in the panel. Cancer scores without a specific malignant phecode "
             "in the panel were excluded (melanoma, matched to CA\\_103, was retained).}")
    L.append("\\label{exttab:prs_crosswalk}")
    L.append("\\begin{tabular}{@{}lll@{}}\\toprule")
    L.append("PRS trait & Standard / Enhanced field & Matched phecode(s) \\\\\\midrule")
    by_trait = {}
    for ph, tr in xwalk.items():
        by_trait.setdefault(tr, []).append(ph)
    for tr in sorted(by_trait):
        s, e = fid.get(tr, ("--", "--"))
        phs = ", ".join(esc(p) for p in by_trait[tr])
        L.append(f"{esc(tr.replace('_',' '))} & {s} / {e} & {phs} \\\\")
    L.append("\\bottomrule\\end{tabular}\\end{table}")

    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT}  ({len(d)} diseases, {len(by_trait)} traits)")


if __name__ == "__main__":
    main()
